version: '3'
services:
  flask-app:
    build:
      context: ./flask-app
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./flask-app:/app
    depends_on:
      - redis
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    volumes:
      - ./worker:/worker
    depends_on:
      - redis
  redis:
    image: redis
